M48
; DRILL file {KiCad 7.0.0} date Sat 04 Mar 2023 18:46:47 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-04T18:46:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X182.917Y-110.2
X182.917Y-118.2
T2
X117.073Y-87.125
X120.325Y-83.873
T0
M30
